name: .NET CI

on:
  push:
    branches: [ BackEnd ]
  pull_request:
    branches: [ BackEnd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Hoặc version bạn đang dùng

      - name: Restore packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests (optional)
        run: dotnet test --no-build || echo "No tests found"
