# .github/workflows/dotnet-ci.yml

name: .NET CI

on:
  push:
    branches: [ main, BackEnd ]
  pull_request:
    branches: [ main, BackEnd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore BloodDonationSystem.sln

    - name: Build project
      run: dotnet build BloodDonationSystem.sln --no-restore --configuration Release

    - name: Run Tests
      working-directory: BloodDonationSystem
      run: dotnet test ./BloodDonationSystem.sln
